version: '3.8'

services:
  db:
    image: postgres:13
    
    ports:
      - "5432:5432"

    env_file: 
      - .env 

    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ~/Desktop/Work/Domitory/db/db_data:/var/lib/postgresql/data
    
    container_name: database

    networks:
      - domitory_network
      